# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 00:17
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=wagtail.wagtailcore.fields.StreamField((('single_image_header', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.StreamBlock((('header_image', wagtail.wagtailimages.blocks.ImageChooserBlock(default='image.jpg', required=True)), ('header_top_text', wagtail.wagtailcore.blocks.CharBlock(default='Top Header Text', required=True)), ('header_sub_text', wagtail.wagtailcore.blocks.CharBlock()), ('header_info_text', wagtail.wagtailcore.blocks.CharBlock()), ('header_cta', wagtail.wagtailcore.blocks.CharBlock(default='Call To Action', required=True)), ('header_target_link', wagtail.wagtailcore.blocks.PageChooserBlock(default='Target URL', required=True))), icon='image', label='Single Image Header')),))), ('rotating_image_header', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.StructBlock((('header_top_text', wagtail.wagtailcore.blocks.CharBlock(default='Top Header Text', required=True)), ('header_sub_text', wagtail.wagtailcore.blocks.CharBlock()), ('header_info_text', wagtail.wagtailcore.blocks.CharBlock())), icon='image', label='Rotating Image Banner')), ('links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('cta', wagtail.wagtailcore.blocks.CharBlock(default='Call To Action', required=True)), ('url_link', wagtail.wagtailcore.blocks.PageChooserBlock(default='Target Url', required=True)))))), ('images', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock(default='image.jpg', required=True))))))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('one_column_highlight', wagtail.wagtailcore.blocks.StructBlock((('column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-left', label='Left column content')),))), ('two_column_highlight', wagtail.wagtailcore.blocks.StructBlock((('left_column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-left', label='Left column content')), ('right_column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-right', label='Right column content'))))), ('three_column_highlight', wagtail.wagtailcore.blocks.StructBlock((('left_column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-left', label='Left column content')), ('center_column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-down', label='Right column content')), ('right_column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-right', label='Right column content')))))), blank=True, null=True),
        ),
    ]
