# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 00:23
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170327_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='header',
            field=wagtail.wagtailcore.fields.StreamField((('single_image_header', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.StreamBlock((('header_image', wagtail.wagtailimages.blocks.ImageChooserBlock(default='image.jpg', required=True)), ('header_top_text', wagtail.wagtailcore.blocks.CharBlock(default='Top Header Text', required=True)), ('header_sub_text', wagtail.wagtailcore.blocks.CharBlock()), ('header_info_text', wagtail.wagtailcore.blocks.CharBlock()), ('header_cta', wagtail.wagtailcore.blocks.CharBlock(default='Call To Action', required=True)), ('header_target_link', wagtail.wagtailcore.blocks.PageChooserBlock(default=999, required=True))), icon='image', label='Single Image Header')),))), ('rotating_image_header', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.StructBlock((('header_top_text', wagtail.wagtailcore.blocks.CharBlock(default='Top Header Text', required=True)), ('header_sub_text', wagtail.wagtailcore.blocks.CharBlock()), ('header_info_text', wagtail.wagtailcore.blocks.CharBlock())), icon='image', label='Rotating Image Banner')), ('links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('cta', wagtail.wagtailcore.blocks.CharBlock(default='Call To Action', required=True)), ('url_link', wagtail.wagtailcore.blocks.PageChooserBlock(default=999, required=True)))))), ('images', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock(default='image.jpg', required=True))))))), blank=True, null=True),
        ),
    ]
