# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:15
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170328_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('one_column_highlight', wagtail.wagtailcore.blocks.StructBlock((('column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-left', label='Left column content')),))), ('two_column_highlight', wagtail.wagtailcore.blocks.StructBlock((('left_column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-left', label='Left column content')), ('right_column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-right', label='Right column content'))))), ('three_column_highlight', wagtail.wagtailcore.blocks.StructBlock((('left_column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-left', label='Left column content')), ('center_column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-down', label='Right column content')), ('right_column', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock())), icon='arrow-right', label='Right column content'))))), ('center_image_well', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.StructBlock((('header_top_text', wagtail.wagtailcore.blocks.CharBlock()), ('header_info_text', wagtail.wagtailcore.blocks.CharBlock())), icon='doc-full', label='Image Well Text')), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(default=0, required=True))))), ('muted_highlight_with_yellow_icons', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.StructBlock((('services_cta', wagtail.wagtailcore.blocks.CharBlock(default='Services', required=True)), ('services_info', wagtail.wagtailcore.blocks.CharBlock())), icon='doc-full', label='Image Well Text')), ('services', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('service_icon', wagtail.wagtailcore.blocks.CharBlock(default='camera', required=True)), ('service_title', wagtail.wagtailcore.blocks.CharBlock(default='service title', required=True)), ('service_desc', wagtail.wagtailcore.blocks.CharBlock(default='service description')))))))))), blank=True, null=True),
        ),
    ]
