# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:24
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170327_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='header',
            field=wagtail.wagtailcore.fields.StreamField((('single_image_header', wagtail.wagtailcore.blocks.StructBlock((('header', wagtail.wagtailcore.blocks.StreamBlock((('header_image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)), ('header_top_text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('header_sub_text', wagtail.wagtailcore.blocks.CharBlock()), ('header_info_text', wagtail.wagtailcore.blocks.CharBlock()), ('header_cta', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('header_target_link', wagtail.wagtailcore.blocks.PageChooserBlock(required=True))), icon='image', label='Single Image Header')),))), ('rotating_image_header', wagtail.wagtailcore.blocks.StructBlock((('text', wagtail.wagtailcore.blocks.StructBlock((('header_top_text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('header_sub_text', wagtail.wagtailcore.blocks.CharBlock()), ('header_info_text', wagtail.wagtailcore.blocks.CharBlock())), icon='image', label='Rotating Image Banner')), ('links', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('cta', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('url_link', wagtail.wagtailcore.blocks.PageChooserBlock(required=True)))))), ('images', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailimages.blocks.ImageChooserBlock(required=True)))))))),
        ),
    ]
